# Turn on validation, so we can use import:
version: ~> 1.0

before_script:
  - if [ "$jit" == "yes" ]; then export RUBYOPT=--jit ; fi ; echo RUBYOPT is $RUBYOPT
  - bundle exec rake compile

script:
  - bundle exec rake test
